ruby/config/routes.rb
Rails.application.routes.draw do
  get 'vendors/Models'

  get 'vendors/States'

  get 'vendors/TypeAdverts'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teches
  resources :categories
  resources :vendors
  resources :models
  resources :states
  resources :type_adverts

  root to: 'home#index'
end

ruby/app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :models
end

ruby/app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  def index
    @vendors = Vendor.all
    @vendor_count = Vendor.joins(models: :teches).group('id').count
  end

  def show
    @models = Model.where(vendor: @vendor)
    @teches = Tech.joins(:model).where(models: {vendor: @vendor})
  end

  def new
    @vendor = Vendor.new
  end

  def edit

  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      redirect_to vendor_path(@vendor), flash: {success: "Добавленно"}
    else
      @error = @vendor.errors.full_messages.first
      render action: 'new' and @error
    end
  end

  def update
    if @vendor.update(vendor_params)
      redirect_to vendor_path(@vendor), flash: {success: 'Обновление прошло успешно'}
    else
      @error = @scheme.errors.full_messages.first
      render action: 'edit' and @error
    end
  end

  def destroy
    begin
      @vendor.destroy
      redirect_to vendors_path, flash: {success: 'Удалено'}
    rescue
      redirect_to vendor_path(@vendor), flash: {error: 'Удалить не возможно'}
    end
  end

  private

  def vendor_params
    params.require(:vendor).permit(:name)
  end

  def set_vendor
    @vendor = Vendor.find(params[:id])
  end
end

ruby/app/helpers/vendors_helper.rb
module VendorsHelper
end

ruby/app/views/vendors/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="bg-white padpad">
        <%= form_for @vendor do |f| %>
          <p>
            <%= f.label :name %>
            <%= f.text_field :name %>
          </p>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

ruby/app/views/vendors/edit.html.erb
<% content_for :head do %>
  <title><%= @vendor.name %></title>
<% end %>

<%= render 'form' %>

ruby/app/views/vendors/index.html.erb
<% content_for :head do %>
  <title>All Vendors</title>
<% end %>
<div class="row">
  <div class="col-md-12">
    <div class="bg-white padpad text-right">
      <%= link_to "Add Vendor", new_vendor_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>
<div class="row">
  <% @vendors.each do |vendor| %>
    <div class="col-md-12">
      <div class="bg-white padpad">
        <%= link_to vendor_path(vendor), class: "Link Link mmm__item-link" do %>
          <h3>
            <%= vendor.name %>
            <font class="mmm__count"> <%= @vendor_count[vendor.id] || 0 %></font>
          </h3>
        <% end %>
      </div>
    </div>

  <% end %>
</div>

ruby/app/views/vendors/new.html.erb
<% content_for :head do %>
  <title>Create Vendor</title>
<% end %>

<%= render 'form' %>

ruby/app/views/vendors/show.html.erb
<% content_for :head do %>
  <title><%= @vendor.name %></title>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="bg-white padpad">
      <div class="row">
        <div class="col-md-8">
          <h4>
            <%= @vendor.name %>
            <font class="mmm__count"> <%= @models.length %></font>
          </h4>
        </div>
        <div class="col-md-4 text-right">
          <div class="btn-group ">
            <%= link_to 'Edit', edit_vendor_path(@vendor), class: 'bnt btn-sm btn-outline-secondary' %>
            <%= link_to 'Delete', vendor_path, method: :delete, class: 'bnt btn-sm btn-outline-secondary', data: {confirm: 'Are you sure?'} %>
          </div>
        </div>
        <% @models.each do |m| %>
          <div class="col-md-1 tree">
            <div class="tree-item">
            </div>
          </div>
          <div class="col-md-11">
            <%= link_to m.name, model_path(m),  class: "Link Link mmm__item-link" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "teches/select" %>