ruby/config/routes.rb
Rails.application.routes.draw do
  get 'vendors/Models'

  get 'vendors/States'

  get 'vendors/TypeAdverts'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teches
  resources :categories
  resources :vendors
  resources :models
  resources :states
  resources :type_adverts

  root to: 'home#index'
end

ruby/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby/app/models/category.rb
class Category < ApplicationRecord
  has_many :teches
end

ruby/app/models/model.rb
class Model < ApplicationRecord
  belongs_to :vendor
  has_many :teches
end

ruby/app/models/state.rb
class State < ApplicationRecord
  has_many :teches
end

ruby/app/models/tech.rb
class Tech < ApplicationRecord
  belongs_to :category
  belongs_to :model
  belongs_to :state
  belongs_to :type_advert
end

ruby/app/models/type_advert.rb
class TypeAdvert < ApplicationRecord
  has_many :teches
end

ruby/app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :models
end

ruby/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @teches = Tech.last 20

    @vendor_count = Vendor.joins(models: :teches).group('id').count
    @vendors = Vendor.all

  end
end

ruby/app/controllers/models_controller.rb
class ModelsController < ApplicationController

  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  def index
    @vendorModels = Hash.new
    @vendors = Vendor.all
    @vendors.each do |v|
      @vendorModels[v] = Model.where(vendor: v)
    end
    @techCount = Model.joins(:teches).group(:id).count
  end

  def show
    @teches = Tech.where(model: @model)
  end

  def new
    @model = Model.new(vendor_id: params[:vendor_id])
  end

  def edit

  end

  def create
    @model = Model.new(model_params)
    if @model.save
      redirect_to model_path(@model), flash: {success: "Добавленно"}
    else
      @error = @model.errors.full_messages.first
      render action: 'new' and @error
    end
  end

  def update
    if @model.update(model_params)
      redirect_to model_path(@model), flash: {success: 'Обновление прошло успешно'}
    else
      @error = @scheme.errors.full_messages.first
      render action: 'edit' and @error
    end
  end

  def destroy
    begin
      @model.destroy
      redirect_to models_path, flash: {success: 'Удалено'}
    rescue
      redirect_to model_path(@model), flash: {error: 'Удалить не возможно'}
    end
  end

  private

  def model_params
    params.require(:model).permit(:name, :vendor_id)
  end

  def set_vendor
    @model = Model.find(params[:id])
  end

end

ruby/app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  def index
    @states = State.all
    @state_count = State.joins(:teches).group('id').count
  end

  def show
    @teches = Tech.where(state: @state)
  end

  def new
    @state = State.new
  end

  def edit

  end

  def create
    @state = State.new(state_params)
    if @state.save
      redirect_to state_path(@state), flash: {success: "Добавленно"}
    else
      @error = @state.errors.full_messages.first
      render action: 'new' and @error
    end
  end

  def update
    if @state.update(state_params)
      redirect_to state_path(@state), flash: {success: 'Обновление прошло успешно'}
    else
      @error = @scheme.errors.full_messages.first
      render action: 'edit' and @error
    end
  end

  def destroy
    begin
      @state.destroy
      redirect_to states_path, flash: {success: 'Удалено'}
    rescue
      redirect_to state_path(@state), flash: {error: 'Удалить не возможно'}
    end
  end

  private

  def state_params
    params.require(:state).permit(:name)
  end

  def set_state
    @state = State.find(params[:id])
  end

end

ruby/app/controllers/teches_controller.rb
class TechesController < ApplicationController

  before_action :set_tech, only: [:show, :edit, :update, :destroy]

  def index
    @teches = Tech.all
  end

  def show

  end

  def new
    @tech = Tech.new
  end

  def edit

  end

  def create
    @tech = Tech.new(tech_params)
    if @tech.save
      redirect_to tech_path(@tech), flash: {success: "Добавленно"}
    else
      @error = @tech.errors.full_messages.first
      
      render action: 'new' and @error
    end
  end

  def update
    if @tech.update(tech_params)
      redirect_to tech_path(@tech), flash: {success: 'Обновление прошло успешно'}
    else
      @error = @scheme.errors.full_messages.first
      render action: 'edit' and @error
    end
  end

  def destroy
    begin
      @tech.destroy
      redirect_to teches_path, flash: {success: 'Удалено'}
    rescue
      redirect_to tech_path(@tech), flash: {error: 'Удалить не возможно'}
    end
  end

  private

  def tech_params
    params.require(:tech).permit(:name, :price, :description, :weight, :year, :hours_use, :mileage_use,
                                 :volume_dvs, :power, :category_id, :model_id, :state_id, :type_advert_id)
  end

  def set_tech
    @tech = Tech.find(params[:id])
  end

end

ruby/app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  def index
    @vendors = Vendor.all
    @vendor_count = Vendor.joins(models: :teches).group('id').count
  end

  def show
    @models = Model.where(vendor: @vendor)
    @teches = Tech.joins(:model).where(models: {vendor: @vendor})
  end

  def new
    @vendor = Vendor.new
  end

  def edit

  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      redirect_to vendor_path(@vendor), flash: {success: "Добавленно"}
    else
      @error = @vendor.errors.full_messages.first
      render action: 'new' and @error
    end
  end

  def update
    if @vendor.update(vendor_params)
      redirect_to vendor_path(@vendor), flash: {success: 'Обновление прошло успешно'}
    else
      @error = @scheme.errors.full_messages.first
      render action: 'edit' and @error
    end
  end

  def destroy
    begin
      @vendor.destroy
      redirect_to vendors_path, flash: {success: 'Удалено'}
    rescue
      redirect_to vendor_path(@vendor), flash: {error: 'Удалить не возможно'}
    end
  end

  private

  def vendor_params
    params.require(:vendor).permit(:name)
  end

  def set_vendor
    @vendor = Vendor.find(params[:id])
  end
end

ruby/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/app/helpers/categories_helper.rb
module CategoriesHelper
end

ruby/app/helpers/home_helper.rb
module HomeHelper
end

ruby/app/helpers/models_helper.rb
module ModelsHelper
end

ruby/app/helpers/states_helper.rb
module StatesHelper
end

ruby/app/helpers/teches_helper.rb
module TechesHelper
end

ruby/app/helpers/type_adverts_helper.rb
module TypeAdvertsHelper
end

ruby/app/helpers/vendors_helper.rb
module VendorsHelper
end

ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', 'data-turbolinks-track' => 'true' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'true' %>
  <%= yield :head %>
</head>

<body>
<div class="container">

  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">

        <%= link_to 'Main page', {controller: 'home', action: 'index'}, class: 'text-muted' %>

      </div>
      <div class="col-4 text-center">
        <span class="blog-header-logo text-dark" href="#">Special Equipment</span>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="text-muted" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3">
            <circle cx="10.5" cy="10.5" r="7.5"></circle>
            <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
          </svg>
        </a>
        <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
      </div>
    </div>
  </header>

  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <%= link_to 'All Tech', teches_path, class: 'p-2 text-muted' %>
      <%= link_to 'All Category', categories_path, class: 'p-2 text-muted' %>
      <%= link_to 'All Vendors', vendors_path, class: 'p-2 text-muted' %>
      <%= link_to 'All Model', models_path, class: 'p-2 text-muted' %>
      <%= link_to 'All State', states_path, class: 'p-2 text-muted' %>
      <%= link_to 'All Type Advert', type_adverts_path, class: 'p-2 text-muted' %>
    </nav>
  </div>




  <% if flash[:error] && flash[:error].length > 0 %>
    <div class="alert alert-danger"><%= flash[:error] %></div>
  <% end %>
  <% if flash[:success] && flash[:success].length > 0 %>
    <div class="alert alert-success"><%= flash[:success] %></div>
  <% end %>
</div>


<div class="container">
  <%= yield %>
</div>

<footer class="container">
  <p class="float-right"><a href="#">Back to top</a></p>
  <p>© 2017-2018 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
</footer>
</body>
</html>