ruby/config/routes.rb
Rails.application.routes.draw do
  get 'vendors/Models'

  get 'vendors/States'

  get 'vendors/TypeAdverts'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teches
  resources :categories
  resources :vendors
  resources :models
  resources :states
  resources :type_adverts

  root to: 'home#index'
end

ruby/app/models/state.rb
class State < ApplicationRecord
  has_many :teches
end

ruby/app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  def index
    @states = State.all
    @state_count = State.joins(:teches).group('id').count
  end

  def show
    @teches = Tech.where(state: @state)
  end

  def new
    @state = State.new
  end

  def edit

  end

  def create
    @state = State.new(state_params)
    if @state.save
      redirect_to state_path(@state), flash: {success: "Добавленно"}
    else
      @error = @state.errors.full_messages.first
      render action: 'new' and @error
    end
  end

  def update
    if @state.update(state_params)
      redirect_to state_path(@state), flash: {success: 'Обновление прошло успешно'}
    else
      @error = @scheme.errors.full_messages.first
      render action: 'edit' and @error
    end
  end

  def destroy
    begin
      @state.destroy
      redirect_to states_path, flash: {success: 'Удалено'}
    rescue
      redirect_to state_path(@state), flash: {error: 'Удалить не возможно'}
    end
  end

  private

  def state_params
    params.require(:state).permit(:name)
  end

  def set_state
    @state = State.find(params[:id])
  end

end

ruby/app/helpers/states_helper.rb
module StatesHelper
end

ruby/app/views/states/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="bg-white padpad">
      <%= form_for @state do |f| %>
        <p>
          <%= f.label :name %>
          <%= f.text_field :name %>
        </p>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

ruby/app/views/states/edit.html.erb
<% content_for :head do %>
  <title><%= @state.name %></title>
<% end %>

<%= render 'form' %>

ruby/app/views/states/index.html.erb
<% content_for :head do %>
  <title>All Models</title>
<% end %>
<div class="row">
  <div class="col-md-12">
    <div class="bg-white padpad text-right">
      <%= link_to "Add State", new_state_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>
<div class="row">
  <% @states.each do |state| %>
    <div class="col-md-12">
      <div class="bg-white padpad">
        <%= link_to state_path(state), class: "Link Link mmm__item-link" do %>
          <h3>
            <%= state.name %>
            <font class="mmm__count"> <%= @state_count[state.id] || 0 %></font>
          </h3>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

ruby/app/views/states/new.html.erb
<% content_for :head do %>
  <title>Create State</title>
<% end %>

<%= render 'form' %>

ruby/app/views/states/show.html.erb
<% content_for :head do %>
  <title><%= @state.name %></title>
<% end %>
<div class="row">
  <div class="col-md-12">
    <div class="bg-white padpad">
      <div class="row">
        <div class="col-md-8">
          <h4>
            <%= @state.name %>
            <font class="mmm__count"> <%= @teches.length %></font>
          </h4>
        </div>
        <div class="col-md-4 text-right">
          <div class="btn-group ">
            <%= link_to 'Edit', edit_state_path(@state), class: 'bnt btn-sm btn-outline-secondary' %>
            <%= link_to 'Delete', state_path, method: :delete, class: 'bnt btn-sm btn-outline-secondary', data: {confirm: 'Are you sure?'} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render template: 'teches/_select' %>