ruby/config/routes.rb
Rails.application.routes.draw do
  get 'vendors/Models'

  get 'vendors/States'

  get 'vendors/TypeAdverts'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teches
  resources :categories
  resources :vendors
  resources :models
  resources :states
  resources :type_adverts

  root to: 'home#index'
end

ruby/app/models/tech.rb
class Tech < ApplicationRecord
  belongs_to :category
  belongs_to :model
  belongs_to :state
  belongs_to :type_advert
end

ruby/app/controllers/teches_controller.rb
class TechesController < ApplicationController

  before_action :set_tech, only: [:show, :edit, :update, :destroy]

  def index
    @teches = Tech.all
  end

  def show

  end

  def new
    @tech = Tech.new
  end

  def edit

  end

  def create
    @tech = Tech.new(tech_params)
    if @tech.save
      redirect_to tech_path(@tech), flash: {success: "Добавленно"}
    else
      @error = @tech.errors.full_messages.first
      
      render action: 'new' and @error
    end
  end

  def update
    if @tech.update(tech_params)
      redirect_to tech_path(@tech), flash: {success: 'Обновление прошло успешно'}
    else
      @error = @scheme.errors.full_messages.first
      render action: 'edit' and @error
    end
  end

  def destroy
    begin
      @tech.destroy
      redirect_to teches_path, flash: {success: 'Удалено'}
    rescue
      redirect_to tech_path(@tech), flash: {error: 'Удалить не возможно'}
    end
  end

  private

  def tech_params
    params.require(:tech).permit(:name, :price, :description, :weight, :year, :hours_use, :mileage_use,
                                 :volume_dvs, :power, :category_id, :model_id, :state_id, :type_advert_id)
  end

  def set_tech
    @tech = Tech.find(params[:id])
  end

end

ruby/app/helpers/teches_helper.rb
module TechesHelper
end

ruby/app/views/teches/_form.html.erb
<%= form_for @tech, :html => {multipart: true} do |f| %>

  <div class="row">
    <div class="col-md-12">
      <div class="bg-white padpad">
        <div class="row">
          <div class="col-md-8 col-sm-12">
            <h3><%= f.text_field :name, placeholder: "Title" %></h3>
            <% unless @tech.created_at.nil? %>
              <span>created: <%= @tech.created_at %></span>
              <span>updated: <%= @tech.updated_at %></span>
            <% end %>
          </div>
          <div class="col-md-4 col-sm-12 text-right">
              <span>
                <%= f.collection_select :type_advert_id, TypeAdvert.all, :id, :name, {promt: 'Select type advert'} %>
                </span>
            <h4><%= f.text_field :price %><sub>₽</sub></h4>
          </div>
        </div>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="col-md-12">
      <div class="bg-white padpad">
        <div class="row">
          <div class="col-md-8 col-sm-12">
            <p>Name: <strong> NAME</strong></p>
          </div>
          <div class="col-md-4 col-sm-12 text-right">
            <button class="btn btn-phone"> Показать
              <p>+7-***-***-****</p></button>
          </div>
        </div>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="col-md-12">
      <div class="bg-white padpad">
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <table class="table">
              <tbody>
              <tr>
                <th scope="row">category</th>
                <td><%= f.collection_select :category_id, Category.all, :id, :name, {promt: "Select category"} %></td>
              </tr>
              <tr>
                <th scope="row">year</th>
                <td><%= f.text_field :year %></td>
              </tr>
              <tr>
                <th scope="row">power</th>
                <td><%= f.text_field :power %></td>
              </tr>
              <tr>
                <th scope="row">volume_dvs</th>
                <td><%= f.text_field :volume_dvs %></td>
              </tr>
              <tr>
                <th scope="row">state</th>
                <td><%= f.collection_select :state_id, State.all, :id, :name, {promt: "Select category"} %></td>
              </tr>
              </tbody>
            </table>
          </div>
          <div class="col-md-6 col-sm-12">
            <table class="table">
              <tbody>
              <tr>
                <th scope="row">vendor</th>
                <td><%= select_tag :model_id, Vendor.all %></td>
              </tr>
              <tr>
                <th scope="row">model</th>
                <td><%= f.grouped_collection_select :model_id, Vendor.all, :models, :name, :id, :name, include_blank: true %></td>
              </tr>
              <tr>
                <th scope="row">weight</th>
                <td><%= f.text_field :weight %> кг.</td>
              </tr>
              <tr>
                <th scope="row">hours_use</th>
                <td><%= f.text_field :hours_use %></td>
              </tr>
              <tr>
                <th scope="row">mileage_use</th>
                <td><%= f.text_field :mileage_use %></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="col-md-12">
      <div class="bg-white padpad">
        <p>
          <%= f.text_area :description %>
        </p>
      </div>
    </div>

    <div class="col-md-12">
      <div class="bg-white padpad text-center">
        <p>
          <%= f.submit class: "btn btn-success" %>
        </p>
      </div>
    </div>
  </div>

<% end %>

ruby/app/views/teches/_select.html.erb
<div class="album py-5 bg-light">
    <div class="row">
      <% @teches.each do |t| %>

        <div class=" col-sm-12 col-md-4">
          <div class="card sm-12 mb-4  box-shadow">
            <%= link_to tech_path(t) do %>
              <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1619a34b18e%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1619a34b18e%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.734375%22%20y%3D%22120.3%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
            <% end %>
            <div class="card-body">

              <%= link_to tech_path(t) do %>
                <h5 class="card-title black"> <%= t.name %> </h5>
              <% end %>
              <h6 class="card-subtitle mb-2 text-muted text-right"> <%= t.price %> р. </h6>
              <p class="card-text"> <%= t.description %> </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'Show', tech_path(t), class: "btn btn-sm btn-outline-secondary" %>
                  <%= link_to 'Edit', edit_tech_path(t), class: 'btn btn-sm btn-outline-secondary' %>
                </div>
                <small class="text-muted"> <%= t.created_at %> </small>
              </div>
            </div>
          </div>
        </div>

      <% end %>
    </div>
</div>

ruby/app/views/teches/edit.html.erb
<% content_for :head do %>
  <title><%= @tech.name %></title>
<% end %>

<%= render 'form' %>

ruby/app/views/teches/index.html.erb
<% content_for :head do %>
  <title>All Teches</title>
<% end %>
<div class="row">
  <div class="col-md-12">
    <div class="bg-white padpad text-right">
      <%= link_to "Add Tech", new_tech_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>
<%= render 'select' %>

ruby/app/views/teches/new.html.erb
<% content_for :head do %>
  <title>Create Tech</title>
<% end %>

<%= render 'form' %>

ruby/app/views/teches/show.html.erb
<% content_for :head do %>
  <title><%= @tech.name %></title>
<% end %>

<div class="container">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://www.bmw.ca/content/dam/bmw/marketCA/bmw_ca/images/Experience_/Driving_Experience/BMW_M-Thermal-Experience_mainteaser_1680x756_Jan2017.jpg/_jcr_content/renditions/cq5dam.resized.img.1680.large.time1515429369333.jpg" alt="First slide">
      </div>
      <div class="carousel-item">
        <img src="https://www.bmw.ca/content/dam/bmw/marketCA/bmw_ca/images/Experience_/Driving_Experience/BMW_M-Thermal-Experience_mainteaser_1680x756_Jan2017.jpg/_jcr_content/renditions/cq5dam.resized.img.1680.large.time1515429369333.jpg" alt="First slide">
      </div>
      <div class="carousel-item">
        <img src="https://www.bmw.ca/content/dam/bmw/marketCA/bmw_ca/images/Experience_/Driving_Experience/BMW_M-Thermal-Experience_mainteaser_1680x756_Jan2017.jpg/_jcr_content/renditions/cq5dam.resized.img.1680.large.time1515429369333.jpg" alt="First slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>


<div class="row">
  <div class="col-md-12">
    <div class="bg-white padpad">
      <div class="row">
        <div class="col-md-8 col-sm-12">
          <h1><%= @tech.name %></h1>
          <span>created: <%= @tech.created_at %></span>
          <span>updated: <%= @tech.updated_at %></span>
        </div>
        <div class="col-md-4 col-sm-12 text-right">
              <span>
                <%= @tech.type_advert.name %>
                </span>
          <h1><%= @tech.price %><sub>₽</sub></h1>
        </div>
      </div>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="col-md-12">
    <div class="bg-white padpad">
      <div class="row">
        <div class="col-md-8 col-sm-12">
          <p>Name: <strong> NAME</strong></p>
        </div>
        <div class="col-md-4 col-sm-12 text-right">
          <button class="btn btn-phone"> Показать
            <p>+7-***-***-****</p></button>
        </div>
      </div>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="col-md-12">
    <div class="bg-white padpad">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <table class="table">
            <tbody>
            <tr>
              <th scope="row">category</th>
              <td><%= @tech.category.name %></td>
            </tr>
            <tr>
              <th scope="row">year</th>
              <td><%= @tech.year %></td>
            </tr>
            <tr>
              <th scope="row">power</th>
              <td><%= @tech.power %></td>
            </tr>
            <tr>
              <th scope="row">volume_dvs</th>
              <td><%= @tech.volume_dvs %></td>
            </tr>
            <tr>
              <th scope="row">state</th>
              <td><%= @tech.state.name %></td>
            </tr>
            </tbody>
          </table>
        </div>
        <div class="col-md-6 col-sm-12">
          <table class="table">
            <tbody>
            <tr>
              <th scope="row">vendor</th>
              <td><%= @tech.model.vendor.name %></td>
            </tr>
            <tr>
              <th scope="row">model</th>
              <td><%= @tech.model.name %></td>
            </tr>
            <tr>
              <th scope="row">weight</th>
              <td><%= @tech.weight %> кг.</td>
            </tr>
            <tr>
              <th scope="row">hours_use</th>
              <td><%= @tech.hours_use %></td>
            </tr>
            <tr>
              <th scope="row">mileage_use</th>
              <td><%= @tech.mileage_use %></td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="col-md-12">
    <div class="bg-white padpad">
      <p>
        <%= @tech.description %>
      </p>
    </div>
  </div>

  <div class="col-md-12">
    <%= link_to 'Edit', edit_tech_path(@tech), :class => 'bnt btn-sm btn-outline-secondary' %>
    <%= link_to 'Delete', tech_path, method: :delete, :class => 'bnt btn-sm btn-outline-secondary', data: {confirm: 'Are you sure?'} %>
  </div>
</div>